# Generated by Django 6.0 on 2026-01-09 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        
        migrations.AlterUniqueTogether(
            name='productvariantitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariantitem',
            name='variant',
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productvariaty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        migrations.DeleteModel(
            name='ProductVariantItem',
        ),
    ]
